### ISSUE TITLE
ODBC returns garbage if no where clause specified and results larger than 10,000 rows

### ISSUE THREAD

**Issue by mnburk** [getryft/ryft-odbc#71]
Limit is set to 10,000 rows.  Tried CSV and XML file types and both have the issue.

**Comment by mnburk** [comment]
SQL> select count(*) from sfdata where adid_value like 'google'
+--------------------+
| EXPR_1             |
+--------------------+
| 25181399           |
+--------------------+
SQLRowCount returns -1
1 rows fetched

**Comment by adleyva** [comment]
issue is associated with ryftx creating empty index and data files whenever the max-count parameter is used.

**Comment by mnburk** [comment]
ryftx fixed - closing issue.
