### ISSUE TITLE
Number search is cast as varchar in SQL - allow for user configurable setting

### ISSUE THREAD

**Issue by adleyva** [getryft/ryft-odbc#78]
Consider  modifying the meta.table as follows and then using the specified data type for the SQL definition.  For example:

     c_customer_sk          = ("C_CUSTOMER_SK", "NUMBER(16,,,."FLOAT")", "")
     c_customer_id          = ("C_CUSTOMER_ID", "VARCHAR(16)", "")
     c_current_cdemo_sk     = ("C_CURRENT_CDEMO_SK", " NUMBER(16,,,.,"INTEGER")", "")
     c_current_hdemo_sk     = ("C_CURRENT_HDEMO_SK", "NUMBER(16,,,."INTEGER”)", "")
     c_current_addr_sk      = ("C_CURRENT_ADDR_SK", "NUMBER(32,,,."DOUBLE")", "")
     c_salutation           = ("C_SALUTATION", "VARCHAR(10)", "")

**Comment by mnburk** [comment]
1. Add type to NUMBER in meta table and convert on output of query to proper type instead of returning varchar.
2. For currency return output of query as a double.

**Comment by adleyva** [comment]
fixed in 2.7.0.4
